package com.zzg.mybatis.generator.plugins;

import org.mybatis.generator.api.GeneratedXmlFile;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.DefaultXmlFormatter;
import org.mybatis.generator.api.dom.xml.Attribute;
import org.mybatis.generator.api.dom.xml.Document;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.codegen.XmlConstants;

import java.util.ArrayList;
import java.util.List;

/**
 * @author 池北鱼
 * @date 2024/5/12 12:32
 */
public class CustomXmlPlugin extends PluginAdapter {

    @Override
    public boolean validate(List<String> warnings) {
        return true;
    }

    @Override
    public List<GeneratedXmlFile> contextGenerateAdditionalXmlFiles(IntrospectedTable introspectedTable) {
        Document document = getDocument(introspectedTable);
        if (document == null) {
            return super.contextGenerateAdditionalXmlFiles(introspectedTable);
        }
        List<GeneratedXmlFile> generatedXmlFiles = new ArrayList<GeneratedXmlFile>();
        GeneratedXmlFile gxf = new GeneratedXmlFile(document, introspectedTable.getMyBatis3XmlMapperFileName().replace("Mapper","CustomMapper"),
                introspectedTable.getMyBatis3XmlMapperPackage(),
                context.getSqlMapGeneratorConfiguration().getTargetProject(), true, context.getXmlFormatter());
        generatedXmlFiles.add(gxf);
        return generatedXmlFiles;
    }

    private Document getDocument(IntrospectedTable introspectedTable) {
        Document document =
                new Document(XmlConstants.MYBATIS3_MAPPER_PUBLIC_ID, XmlConstants.MYBATIS3_MAPPER_SYSTEM_ID);
        document.setRootElement(getSqlMapElement(introspectedTable));
        if (!context.getPlugins().sqlMapDocumentGenerated(document, introspectedTable)) {
            document = null;
        }

        return document;
    }

    private XmlElement getSqlMapElement(IntrospectedTable introspectedTable) {
        XmlElement root = new XmlElement("mapper"); //$NON-NLS-1$
        String namespace = introspectedTable.getMyBatis3SqlMapNamespace();
        root.addAttribute(new Attribute("namespace", //$NON-NLS-1$
                namespace));
        context.getCommentGenerator().addRootComment(root);
        root.addElement(new TextElement("<!-- This sql is auto-generated by MyBatis Generator. -->")); //$NON-NLS-1$
        return root;
    }

}
